// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGM0Tu4Q-CWXDnZpv0tBRG2ZVi41dORl0',
    appId: '1:236018409371:web:32da3c15964630cde1cb3e',
    messagingSenderId: '236018409371',
    projectId: 'frankie-elvis-app-55dc0',
    authDomain: 'frankie-elvis-app-55dc0.firebaseapp.com',
    storageBucket: 'frankie-elvis-app-55dc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5jp7XMO23zEnV13VDZBpUj_iMDcw3CA',
    appId: '1:236018409371:android:bb84be55c399721ce1cb3e',
    messagingSenderId: '236018409371',
    projectId: 'frankie-elvis-app-55dc0',
    storageBucket: 'frankie-elvis-app-55dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO7ZTEY8jmPPGp6ZwQyEIiUUyXf2VPOWQ',
    appId: '1:236018409371:ios:88ba3756e532f095e1cb3e',
    messagingSenderId: '236018409371',
    projectId: 'frankie-elvis-app-55dc0',
    storageBucket: 'frankie-elvis-app-55dc0.firebasestorage.app',
    iosBundleId: 'com.example.frankieAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO7ZTEY8jmPPGp6ZwQyEIiUUyXf2VPOWQ',
    appId: '1:236018409371:ios:88ba3756e532f095e1cb3e',
    messagingSenderId: '236018409371',
    projectId: 'frankie-elvis-app-55dc0',
    storageBucket: 'frankie-elvis-app-55dc0.firebasestorage.app',
    iosBundleId: 'com.example.frankieAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGM0Tu4Q-CWXDnZpv0tBRG2ZVi41dORl0',
    appId: '1:236018409371:web:ffaeaa4dcc7b6bb2e1cb3e',
    messagingSenderId: '236018409371',
    projectId: 'frankie-elvis-app-55dc0',
    authDomain: 'frankie-elvis-app-55dc0.firebaseapp.com',
    storageBucket: 'frankie-elvis-app-55dc0.firebasestorage.app',
  );
}
